# Xamarin.Android and Xamarin.IOS

# Build a Xamarin.Android and Xamarin.IOS project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin


trigger:
- master
jobs:
  #Job Android
  - job: Android
    pool:
      vmImage: 'macos-latest'

  #Release setzten
    variables:
      buildConfiguration: 'Release'
      outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

    steps:
    #NuGet Installieren
    - task: NuGetToolInstaller@1

    #NuGet 
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'

    #Android bauen
    - task: XamarinAndroid@1
      inputs:
        projectFile: '**/*droid*.csproj'
        outputDirectory: '$(outputDirectory)'
        configuration: '$(buildConfiguration)'
    
    #Android Signen
    - task: AndroidSigning@3
      inputs:
        apkFiles: '**/*.apk'
        apksign: true
        apksignerKeystoreFile: 'EarablesKIT.keystore'
        apksignerKeystorePassword: '$(keystorepasswordEarables)'
        apksignerKeystoreAlias: 'TestingAzure'
        apksignerKeyPassword: '$(keystorepasswordEarables)'

    
  - job: iOS
    pool:
      vmImage: 'macOS 10.13'

    steps:
    - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_4_1 
      displayName: 'Select Xamarin SDK version'
      enabled: false

    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'

    - task: XamariniOS@2
      inputs:
        solutionFile: '**/*.sln'
        configuration: 'Release'
        buildForSimulator: true
        packageApp: false
